version: '3.8'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda42-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: npm run start
    working_dir: /app
    restart: unless-stopped